### ISSUE TITLE
Sharing your custom app

### ISSUE THREAD

**Issue by 3raxton** [JakeRoggenbuck/spicetify-cli-extensions#3]
Hey there,

I've seen your custom app for Spicetify and understand the struggle of getting them out to users. I've recently created a community based repo for developers of customs apps to share their apps. 

If you're interested in creating a pull request to share your custom app with others who are searching for different custom apps for Spicetify, feel free! 

Please don't feel required to create a pull request. However, I figured I'd share the repo with you since you've created a custom app, and you may be interested in getting it out to users. 

https://github.com/3raxton/spicetify-custom-apps

Cheers!

**Comment by JakeRoggenbuck** [comment]
Hi, 

Apologies for not getting to this until now. I really like the idea of a community repo and I'm excited by your project!
I just made a PR on your repo, and I might PR some more sometime in the future.

Thanks!

**Comment by 3raxton** [comment]
No problem, thanks for making a PR! I'm going to leave a comment on your PR that aligns with the information below. 

To make this as clean as possible for the community, I've implemented a few different requirements for PRs, including contribution guidelines and an attribution page for authors.

Would you mind adding your custom app to a folder with the README and respective files to make it easier for community members to find? Moreover, if you'd like, feel free to add your custom app and attribution details to the AUTHORS.md file, that would be awesome! 

As for the changes, you can read more details here: https://github.com/3raxton/spicetify-custom-apps/pull/2#pullrequestreview-570786958

I'm glad you're one of the few kicking off this project!
